import user_xml_updater


def modify_items(self, items):
    """User defined implementation for JssDoc in jss_doc.py. Meant to allow user to modify the data that gets
    autogenerated for the document.

    Args:
        self: JssDoc's self.
        items (tuple list): Data to be included in document.

    Returns:
        void

    Examples:
        items.insert(3, ("Extra data", 123))
    """
    prev_name = self.jss_server.get_extension_attribute(self.computer.jss_id, name="Previous Computer Names")
    items.insert(1, ("Prev Name", prev_name))


def update_offboard_config(self):
    """User defines implementation. Meant to update the computer's JSS record with extra information before
    offboarding.
    """
    # <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
    # Append the computer name with the serial number.
    self._offboard_config = user_xml_updater.append_name(self._computer.get_serial(), self._offboard_config)
    # <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
    # Add a timestamp to the additional notes attribute.
    self._offboard_config = user_xml_updater.timestamp_note(self._offboard_config)
    # <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
    # Set the previous computer name extension attribute.
    self._offboard_config = user_xml_updater.set_previous_computer_name(self._computer.jss_name, self._offboard_config)
